---
name: chain-workflow
run-name: "This should run after success"
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Test]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 
        run: |
          echo "hello from the other workflow"

